VinCity/VinCity.CMS/Controllers/HomeController.cs
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using VinCity.CMS.Common;
using VinCity.Models.Entities;
using VinCtity.CMS.Repository;

namespace VinCity.CMS.Controllers
{
    public class HomeController : Controller
    {
        private VinCityEntities db = new VinCityEntities();
        private GenericUnitOfWork _unitOfWork = new GenericUnitOfWork();

        private ApplicationUserManager _userManager;
        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        private ApplicationRoleManager _roleManager;
        public ApplicationRoleManager RoleManager
        {
            get
            {
                return _roleManager ?? HttpContext.GetOwinContext().Get<ApplicationRoleManager>();
            }
            private set
            {
                _roleManager = value;
            }
        }
        public ActionResult Index()
        {

            List<Article> listArticle = db.Articles.Where(x => x.Status == (int)CMS_STATUS.ACTIVE && x.CategoryId == 1).OrderByDescending(o => o.Id).Take(4).ToList();
            if (listArticle.Count > 4)
            {
                listArticle.RemoveRange(0, 4);
            }
            ViewBag.ArticleOlder = listArticle;

            List<Article> listArticleProject = db.Articles.Where(x => x.Status == (int)CMS_STATUS.ACTIVE && x.CategoryId == 2).OrderByDescending(o => o.Id).Take(10).ToList();
            ViewBag.listProject = listArticleProject;

            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

VinCity/VinCity.CMS/Controllers/TinTucController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using VinCity.CMS.Common;
using VinCity.Models.Entities;

namespace VinCity.CMS.Controllers
{
    public class TinTucController : Controller
    {
        private VinCityEntities db = new VinCityEntities();
        // GET: TinTuc
        public ActionResult Index()
        {
            var articles = db.Articles.ToList();
            return View(articles);
        }
        // GET: News/Details/5
        public ActionResult Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Article articles = db.Articles.Find(id);
            if (articles == null)
            {
                return HttpNotFound();
            }
            ViewBag.CurrentCateId = articles.Category.Id > 0 ? articles.Category.Id : 0;
            ViewBag.RelatedNews = db.Articles.Where(x => x.CategoryId == articles.CategoryId
                && x.Id != articles.Id && articles.Status == (int)CMS_STATUS.ACTIVE);
            return View(articles);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

VinCity/VinCity.CMS/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

VinCity/VinCity.CMS/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

VinCity/VinCity.CMS/Views/Home/_PartialAbout.cshtml
<section data-id="532405c7" class="elementor-element elementor-element-532405c7 elementor-section-boxed elementor-section-height-default elementor-section-height-default elementor-section elementor-top-section jet-parallax-section" data-settings="{&quot;background_background&quot;:&quot;classic&quot;,&quot;shape_divider_top&quot;:&quot;arrow&quot;}" data-element_type="section">
    <div class="elementor-shape elementor-shape-top" data-negative="false">
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 700 10" preserveAspectRatio="none">
            <path class="elementor-shape-fill" d="M350,10L340,0h20L350,10z"></path>
        </svg>
    </div>
    <div class="elementor-container elementor-column-gap-default">
        <div class="elementor-row">
            <div data-id="20d0c3a7" class="elementor-element elementor-element-20d0c3a7 elementor-column elementor-col-100 elementor-top-column" data-element_type="column">
                <div class="elementor-column-wrap elementor-element-populated">
                    <div class="elementor-widget-wrap">
                        <section data-id="6ceac75f" class="elementor-element elementor-element-6ceac75f elementor-section-boxed elementor-section-height-default elementor-section-height-default elementor-section elementor-inner-section jet-parallax-section" data-element_type="section">
                            <div class="elementor-container elementor-column-gap-default">
                                <div class="elementor-row">
                                    <div data-id="32312fa5" class="elementor-element elementor-element-32312fa5 elementor-column elementor-col-50 elementor-inner-column" data-element_type="column">
                                        <div class="elementor-column-wrap elementor-element-populated">
                                            <div class="elementor-widget-wrap">
                                                <div data-id="1f82f9f7" class="elementor-element elementor-element-1f82f9f7 animated animated-slow elementor-widget elementor-widget-image fadeInLeft" data-settings="{&quot;_animation&quot;:&quot;fadeInLeft&quot;}" data-element_type="image.default">
                                                    <div class="elementor-widget-container">
                                                        <div class="elementor-image">
                                                            <a href="~/Content/Vin/vi-tri-vincity-athena-gia-lam.png" data-elementor-open-lightbox="default">
                                                                <img width="500" height="293" src="~/Content/Vin/vi-tri-vincity-athena-gia-lam.png" class="attachment-full size-full" alt="" srcset="https://ibatdongsan.co/wp-content/uploads/2018/06/vi-tri-vincity-athena-gia-lam.png 500w, https://ibatdongsan.co/wp-content/uploads/2018/06/vi-tri-vincity-athena-gia-lam-300x176.png 300w" sizes="(max-width: 500px) 100vw, 500px">
                                                            </a>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div data-id="3b91d6ba" class="elementor-element elementor-element-3b91d6ba elementor-column elementor-col-50 elementor-inner-column" data-element_type="column">
                                        <div class="elementor-column-wrap elementor-element-populated">
                                            <div class="elementor-widget-wrap">
                                                <div data-id="754c9e88" class="elementor-element elementor-element-754c9e88 animated elementor-widget elementor-widget-heading fadeInRight" data-settings="{&quot;_animation&quot;:&quot;fadeInRight&quot;}" data-element_type="heading.default">
                                                    <div class="elementor-widget-container">
                                                        <h2 class="elementor-heading-title elementor-size-default">VỊ TRÍ TRUNG TÂM KẾT NỐI THUẬN TIỆN</h2>
                                                    </div>
                                                </div>
                                                <div data-id="2311a9b7" class="elementor-element elementor-element-2311a9b7 animated elementor-widget elementor-widget-divider fadeInRight" data-settings="{&quot;_animation&quot;:&quot;fadeInRight&quot;}" data-element_type="divider.default">
                                                    <div class="elementor-widget-container">
                                                        <div class="elementor-divider">
                                                            <span class="elementor-divider-separator"></span>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div data-id="68b3d31a" class="elementor-element elementor-element-68b3d31a animated animated-slow elementor-hidden-tablet elementor-widget elementor-widget-text-editor fadeInRight" data-settings="{&quot;_animation&quot;:&quot;fadeInRight&quot;}" data-element_type="text-editor.default">
                                                    <div class="elementor-widget-container">
                                                        <div class="elementor-text-editor elementor-clearfix"><p><strong>Chung cư VinCity Athena Gia Lâm</strong> nằm tại Gia Lâm – Long Biên, thành Phố Hà Nội, một trong những vị trí vàng trung tâm của quận Long Biên, đây đang là một trong những dự án mới của tập đoàn Vingroup làm chủ đầu tư với mục đích biến chung cư VinCity Gia Lâm thành một trong những dự án hot nhất khu vực Gia Lâm. Khu vực này tuy không phải là khu trung tâm thủ đô nhưng do có hệ thống cơ sở hạ tầng giao thông đồng bộ và nằm gần một số trục đường huyết điểm như Nguyễn Văn Cừ, Ngọc Lâm, Xuân Quan nên việc di chuyển vào trung tâm thành phố là vô cùng dễ dàng. Hơn thế nữa hiện nay do nhu cầu công việc bắt buộc nên rất nhiều các khách hàng từ các tỉnh thành phố khác tới đây sinh sống nên việc chung cư VinCity Gia Lâm gần cầu Chương Dương và cầu Long Biên nên vô cùng dễ dàng đi tới các tỉnh thành phố lân cận.</p></div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </section>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

VinCity/VinCity.CMS/Views/Home/_PartialNew.cshtml
@using VinCity.Models.Entities;
@using VinCity.CMS.Common;
@model IEnumerable<Article>
@{

    List<Article> lstArticleOlder = new List<Article>();
    if (ViewBag.ArticleOlder != null)
    {
        lstArticleOlder = (List<Article>)ViewBag.ArticleOlder;
    }
}


<section data-id="54df52f3" class="elementor-element elementor-element-54df52f3 elementor-section-boxed elementor-section-height-default elementor-section-height-default elementor-section elementor-top-section jet-parallax-section" data-settings="{&quot;background_background&quot;:&quot;classic&quot;}" data-element_type="section">
    <div class="elementor-container elementor-column-gap-no">
        <div class="elementor-row">
            <div data-id="14d2e6f7" class="elementor-element elementor-element-14d2e6f7 elementor-column elementor-col-100 elementor-top-column" data-element_type="column">
                <div class="elementor-column-wrap elementor-element-populated">
                    <div class="elementor-widget-wrap">
                        <div data-id="2a86d406" class="elementor-element elementor-element-2a86d406 animated elementor-widget elementor-widget-heading fadeInDown" data-settings="{&quot;_animation&quot;:&quot;fadeInDown&quot;}" data-element_type="heading.default">
                            <div class="elementor-widget-container">
                                <h2 class="elementor-heading-title elementor-size-default"><a title="Tin tức" href="#">Tin tức</a> &amp; Sự kiện</h2>
                            </div>
                        </div>
                        <div data-id="327bb115" class="elementor-element elementor-element-327bb115 animated elementor-widget elementor-widget-divider fadeInDown" data-settings="{&quot;_animation&quot;:&quot;fadeInDown&quot;}" data-element_type="divider.default">
                            <div class="elementor-widget-container">
                                <div class="elementor-divider">
                                    <span class="elementor-divider-separator"></span>
                                </div>
                            </div>
                        </div>
                        <div data-id="4577566c" class="elementor-element elementor-element-4577566c animated elementor-widget elementor-widget-text-editor fadeInDown" data-settings="{&quot;_animation&quot;:&quot;fadeInDown&quot;}" data-element_type="text-editor.default">
                            <div class="elementor-widget-container">
                                <div class="elementor-text-editor elementor-clearfix"><p>Chúng tôi luôn mang đến những thông tin và <a title="chính sách" href="#">chính sách</a> mới nhất về dự án <a href="#">Vi</a>ncity Athena Gia Lâm.</p></div>
                            </div>
                        </div>
                        <div data-id="2410cc4a" class="elementor-element elementor-element-2410cc4a elementor-grid-4 elementor-grid-tablet-2 elementor-grid-mobile-1 elementor-posts--thumbnail-top elementor-posts--align-center animated elementor-widget elementor-widget-posts fadeInUp" data-settings="{&quot;classic_columns&quot;:&quot;4&quot;,&quot;_animation&quot;:&quot;fadeInUp&quot;,&quot;classic_columns_tablet&quot;:&quot;2&quot;,&quot;classic_columns_mobile&quot;:&quot;1&quot;}" data-element_type="posts.classic">
                            <div class="elementor-widget-container">
                                <div class="elementor-posts-container elementor-posts elementor-grid elementor-posts--skin-classic elementor-has-item-ratio">
                                    @foreach (Article item in lstArticleOlder)
                                    {
                                        <article class="elementor-post elementor-grid-item post-19892 post type-post status-publish format-standard has-post-thumbnail hentry ast-article-single">
                                            <a class="elementor-post__thumbnail__link" href="@Url.Action("Details","News",new { id = SlugHelper.GenerateSlug(item.Id, item.Title) })">
                                                <div class="elementor-post__thumbnail elementor-fit-height">
                                                    <img width="300" height="164" src="~/Uploads/TinTuc/@item.ThumbURL" class="attachment-medium size-medium" alt="" sizes="(max-width: 300px) 100vw, 300px">
                                                </div>
                                            </a>
                                            <div class="elementor-post__text">
                                                <h4 class="elementor-post__title">
                                                    <a href="@Url.Action("Details","TinTuc",new { id = SlugHelper.GenerateSlug(item.Id, item.Title) })">
                                                        @item.Title
                                                    </a>
                                                </h4>
                                                <div class="elementor-post__meta-data">
                                                    <span class="elementor-post-author">
                                                        @if (item.CreateBy != null)
                                                        {
                                                            @item.CreateBy
                                                        }
                                                    </span>
                                                    <span class="elementor-post-date">
                                                        @item.CreateAt
                                                    </span>
                                                </div>
                                                <div class="elementor-post__excerpt">
                                                    <p>@Html.Raw(item.Summary)</p>
                                                </div>
                                            </div>
                                        </article>
                                    }

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>