VinCity/VinCity.CMS/Areas/Admin/Models/CategoriesViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using VinCity.Models.Entities;

namespace VinCity.CMS.Areas.Admin.Models
{
    public class CategoriesViewModel
    {
        public Category categoryInfo { get; set; }
        public bool isMenu { get; set; }
        public Category parentCategory { get; set; }
    }
}

VinCity/VinCity.CMS/Areas/Admin/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using VinCity.CMS.Areas.Admin.Models;
using VinCity.CMS.Common;
using VinCity.Models.Entities;

namespace VinCity.CMS.Areas.Admin.Controllers
{
    public class CategoriesController : Controller
    {
        private VinCityEntities db = new VinCityEntities();

        // GET: Admin/Categories
        public ActionResult Index()
        {
            var lstData = db.Category.ToList();
            var lstNew = new List<CategoriesViewModel>();
            foreach (Category cate in lstData)
            {
                var cateViewModel = new CategoriesViewModel();
                cateViewModel.categoryInfo = cate;
                cateViewModel.parentCategory = db.Category.Find(cate.ParentId);
                if (cate.Type == 1)
                {
                    cateViewModel.isMenu = true;
                }
                else
                {
                    cateViewModel.isMenu = false;
                }
                lstNew.Add(cateViewModel);
            }
            return View(lstNew);
        }
        [ChildActionOnly]
        public Category getCategory(int cateId)
        {
            Category category = db.Category.Find(cateId);
            return category;
        }
        // GET: Categories/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.Category.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        // GET: Categories/Create
        public ActionResult Create()
        {
            ViewBag.Status = Utitlitys.StatusToList();
            ViewBag.CategoryId = new SelectList(db.Category.ToList(), "Id", "Name");
            return View();
        }

        // POST: Categories/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CategoriesViewModel category)
        {
            if (ModelState.IsValid)
            {
                category.categoryInfo.CreateAt = DateTime.Now;
                category.categoryInfo.CreateBy = User.Identity.Name;
                if (category.isMenu == true)
                {
                    category.categoryInfo.Type = 1;
                }
                else
                {
                    category.categoryInfo.Type = 0;
                }
                db.Category.Add(category.categoryInfo);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            //   ViewBag.ParentId = new SelectList(db.Category.ToList(), "Id", "Name",category.ParentId);
            return View(category);
        }

        // GET: Categories/Edit/5
        public ActionResult Edit(int? id)
        {
            ViewBag.Status = Utitlitys.StatusToList();
            ViewBag.CategoryId = new SelectList(db.Category.ToList(), "Id", "Name");
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.Category.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            CategoriesViewModel viewModel = new CategoriesViewModel();
            viewModel.categoryInfo = category;
            if (viewModel.isMenu == true)
            {
                viewModel.categoryInfo.Type = 1;
            }
            else
            {
                viewModel.categoryInfo.Type = 0;
            }

            return View(viewModel);
        }

        // POST: Categories/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(CategoriesViewModel category)
        {
            if (ModelState.IsValid)
            {
                category.categoryInfo.UpdateAt = DateTime.Now;
                category.categoryInfo.UpdateBy = User.Identity.Name;
                db.Entry(category.categoryInfo).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(category);
        }

        // GET: Categories/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.Category.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        // POST: Categories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Category category = db.Category.Find(id);
            db.Category.Remove(category);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

VinCity/VinCity.CMS/Areas/Admin/Views/Categories/Create.cshtml
@using VinCity.Models.Entities;
@using VinCity.CMS.Areas.Admin.Models;
@model CategoriesViewModel
@{
    ViewBag.Title = "thêm mới chuyên mục";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Thêm mới chuyên mục</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <label class="control-label col-md-2">Chuyên mục cha</label>
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.categoryInfo.ParentId, (SelectList)ViewBag.CategoryId, "---Chuyên mục cha---", new { @class = "form-control", @style = "witdth:150px;" })
                @Html.ValidationMessageFor(model => model.categoryInfo.ParentId, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-2">Tên chuyên mục</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.categoryInfo.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.categoryInfo.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Linh liên kết</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.categoryInfo.URL, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.categoryInfo.URL, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Là Menu</label>
            <div class="col-md-10">
                @Html.CheckBoxFor(model => model.isMenu)
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Trạng thái</label>
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.categoryInfo.Status, (SelectList)ViewBag.Status, new { @class = "form-control", @style = "witdth:150px;" })
                @Html.ValidationMessageFor(model => model.categoryInfo.Status, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-info btn-sm" />
                &nbsp;&nbsp;
                @Html.ActionLink("Quay lại danh sách", "Index", null, new { @class = "btn btn-info btn-sm" })
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

VinCity/VinCity.CMS/Areas/Admin/Views/Categories/Delete.cshtml
@model VinCity.Models.Entities.Category

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Category</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.URL)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.URL)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Type)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ParentId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ParentId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreateBy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreateBy)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreateAt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreateAt)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UpdateBy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UpdateBy)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UpdateAt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UpdateAt)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

VinCity/VinCity.CMS/Areas/Admin/Views/Categories/Details.cshtml
@using VinCity.Models.Entities;
@using VinCity.CMS.Areas.Admin.Models;
@model Category

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Chuyên mục</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Tên chuyên mục
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            Linh liên kết
        </dt>

        <dd>
            @Html.DisplayFor(model => model.URL)
        </dd>

        <dt>
            Menu
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Type)
        </dd>

        <dt>
            Trạng thái
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

        <dt>
            Chuyên mục cha
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ParentId)
        </dd>

        <dt>
            Người tạo
            @*@Html.DisplayNameFor(model => model.CreateBy)*@
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreateBy)
        </dd>

        <dt>
            Ngày tạo
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreateAt)
        </dd>

        <dt>
            Cập nhật bởi
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UpdateBy)
        </dd>

        <dt>
            Ngày cập nhật
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UpdateAt)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }, new { @class = "btn btn-info btn-sm" }) &nbsp;&nbsp;
    @Html.ActionLink("Quay lại danh sách", "Index", null, new { @class = "btn btn-info btn-sm" })
</p>

VinCity/VinCity.CMS/Areas/Admin/Views/Categories/Edit.cshtml
@using VinCity.Models.Entities;
@using VinCity.CMS.Areas.Admin.Models;
@model CategoriesViewModel

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Chuyên mục</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.categoryInfo.Id)

        <div class="form-group">
            <label class="control-label col-md-2" for="Name">Tên chuyên mục</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.categoryInfo.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.categoryInfo.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2" for="URL">Linh liên kết</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.categoryInfo.URL, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.categoryInfo.URL, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2" for="Type">Menu</label>
            <div class="col-md-10">
                @Html.CheckBoxFor(model => model.isMenu)
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2" for="Status">Trạng thái</label>
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.categoryInfo.Status, (SelectList)ViewBag.Status, new { @class = "form-control", @style = "witdth:150px;" })
                @Html.ValidationMessageFor(model => model.categoryInfo.Status, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2" for="ParentId">Chuyên mục cha</label>
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.categoryInfo.ParentId, (SelectList)ViewBag.CategoryId, "---Chuyên mục cha---", new { @class = "form-control", @style = "witdth:150px;" })
                @Html.ValidationMessageFor(model => model.categoryInfo.ParentId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-info btn-sm" />
                &nbsp;&nbsp;
                @Html.ActionLink("Quay lại danh sách", "Index", null, new { @class = "btn btn-info btn-sm" })
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

VinCity/VinCity.CMS/Areas/Admin/Views/Categories/Index.cshtml
@using VinCity.Models.Entities;
@using VinCity.CMS.Common;
@using VinCity.CMS.Areas.Admin.Models;
@model IEnumerable<CategoriesViewModel>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Index</h2>

<p style="margin-top: 10px;">
    @Html.ActionLink("Thêm mới", "Create", "Categories", null, new { @class = "btn btn-info btn-sm" })
</p>
<table class="wapperpager table table-bordered table-hover dataTable">
    <tr>
        <th>
            Tên chuyên mục
        </th>
        <th>
            Linh liên kết
        </th>
        <th>
            Menu
        </th>
        <th>
            Trạng thái
        </th>
        <th>
            Chuyên mục cha
        </th>
        <th>
            Người tạo
        </th>
        <th>
            Ngày tạo
        </th>
        <th></th>
        <th>
            Ngày cập nhật
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.categoryInfo.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.categoryInfo.URL)
            </td>
            <td>
                @item.isMenu.ToString()
            </td>
            <td>
                @*@Utitlitys.StatusToString(item.categoryInfo.Status.Value)*@
            </td>
            <td>
                @*@controller.getCategory(item.ParentId.Value).Name*@
                @if (item.parentCategory == null)
                {
                    <span> --- </span>
                }
                else
                {
                    @Html.DisplayFor(modelItem => item.parentCategory.Name)
                }

            </td>
            <td>
                @Html.DisplayFor(modelItem => item.categoryInfo.CreateBy)
            </td>
            <td>
                @item.categoryInfo.CreateAt
                @*@Utitlitys.DatetimeToVN(item.categoryInfo.CreateAt.Value)*@
            </td>
            <td>
                @*@Html.DisplayFor(modelItem => item.UpdateBy)*@
            </td>
            <td>
                @item.categoryInfo.UpdateAt
                @*@Html.DisplayFor(modelItem => item.UpdateAt)*@
            </td>
            <td style="white-space:nowrap">
                <a href='@Url.Action("Edit", "Categories", new { id = item.categoryInfo.Id })'><img src="~/Images/icons/page_white_edit.png" title="Cập nhật" /></a> |
                <a href='@Url.Action("Delete", "Categories",new { id = item.categoryInfo.Id })'><img src="~/Images/icons/bin_closed.png" title="Xóa thông tin" /></a>
            </td>
        </tr>
    }

</table>