VinCity/VinCity.CMS/Areas/Admin/Models/ArticleViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using VinCity.Models.Entities;

namespace VinCity.CMS.Areas.Admin.Models
{
    public class ArticleViewModel
    {
        public Article articleInfo { get; set; }
        public List<SelectListItem> statusArticles { get; set; }
        [AllowHtml]
        public string Description { get; set; }

        [AllowHtml]
        public string Summary { get; set; }

        [AllowHtml]
        public string Description_EN { get; set; }

        [AllowHtml]
        public string Summary_EN { get; set; }

    }
}

VinCity/VinCity.CMS/Areas/Admin/Controllers/ArticlesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using VinCity.CMS.Areas.Admin.Models;
using VinCity.CMS.Common;
using VinCity.Models.Entities;

namespace VinCity.CMS.Areas.Admin.Controllers
{
    public class ArticlesController : Controller
    {
        private VinCityEntities db = new VinCityEntities();

        // GET: Admin/Articles
        public ActionResult Index()
        {
            var articles = db.Articles.Include(a => a.Category).OrderByDescending(o => o.Id);
            return View(articles.ToList());
        }

        // GET: Articles/Details/5
        public ActionResult Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Article articles = db.Articles.Find(id);
            if (articles == null)
            {
                return HttpNotFound();
            }
            return View(articles);
        }

        // GET: Articles/Create
        public ActionResult Create()
        {
            ViewBag.Status = Utitlitys.StatusToList();

            List<Category> listITem = new List<Category>();
            List<Category> listCateParent;
            List<Category> listCateChild;
            Category dopDowItem;
            listCateParent = db.Category.Where(o => o.ParentId == null).OrderBy(o => o.Id).ToList();

            foreach (Category item in listCateParent)
            {
                dopDowItem = new Category();
                listCateChild = db.Category.Where(o => o.ParentId == item.Id).ToList();
                if (listCateChild.Count > 0)
                {
                    listITem.Add(item);
                    foreach (Category itemCchild in listCateChild)
                    {
                        itemCchild.Name = "---- " + itemCchild.Name;
                        listITem.Add(itemCchild);
                    }
                }
                else
                {
                    listITem.Add(item);
                }
            }

            ViewBag.CategoryId = new SelectList(listITem, "Id", "Name");
            return View();
        }

        // POST: Articles/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [System.Web.Mvc.HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult Create(ArticleViewModel articles, IEnumerable<HttpPostedFileBase> files)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var fileName = string.Empty;
                    if (files != null)
                    {
                        foreach (var file in files)
                        {
                            if (file != null && file.ContentLength > 0)
                            {
                                //kiem tra file extension lan nua
                                List<string> excelExtension = new List<string>();
                                excelExtension.Add(".png");
                                excelExtension.Add(".jpg");
                                excelExtension.Add(".gif");
                                var extension = Path.GetExtension(file.FileName);
                                if (!excelExtension.Contains(extension.ToLower()))
                                {
                                    return Json(new { success = 0, message = "File không đúng định dạng cho phép, bạn hãy chọn file có định dạng .jpg, gif hoặc png" });
                                }
                                //kiem tra dung luong file
                                var fileSize = file.ContentLength;
                                var fileMB = (fileSize / 1024f) / 1024f;
                                if (fileMB > 5)
                                {
                                    return Json(new { success = 0, message = "Dung lượng ảnh không được lớn hơn 5MB" });
                                }
                                // luu ra dia
                                fileName = Path.GetFileNameWithoutExtension(file.FileName);
                                //fileName = fileName + "_" + user.UserID + extension;
                                fileName = fileName + "-" + DateTime.Now.ToString("dd-MM-yy-hh-ss") + extension;
                                var physicalPath = Path.Combine(Server.MapPath("~/Uploads/TinTuc"), fileName);
                                file.SaveAs(physicalPath);
                                articles.articleInfo.ThumbURL = fileName;
                            }
                        }
                    }
                    articles.articleInfo.Summary = articles.Summary;
                    articles.articleInfo.Description = articles.Description;
                    articles.articleInfo.Summary_EN = articles.Summary_EN;
                    articles.articleInfo.Description_EN = articles.Description_EN;
                    articles.articleInfo.CreateAt = DateTime.Now;
                    articles.articleInfo.CreateBy = User.Identity.Name;
                    articles.articleInfo.Category = db.Category.Find(articles.articleInfo.CategoryId);
                    db.Articles.Add(articles.articleInfo);
                    db.SaveChanges();
                    TempData["info"] = "Thêm bài viết thành công";
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    TempData["error"] = "Lỗi thêm bài viết: " + ex.Message;
                }
            }

            ViewBag.CategoryId = new SelectList(db.Category, "Id", "Name", articles.articleInfo.CategoryId);
            return View(articles);
        }

        // GET: Articles/Edit/5
        public ActionResult Edit(long? id)
        {
            ViewBag.Status = Utitlitys.StatusToList();
            //ViewBag.CategoryId = new SelectList(db.Category, "Id", "Name");
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Article articles = db.Articles.Find(id);
            if (articles == null)
            {
                return HttpNotFound();
            }

            List<Category> listITem = new List<Category>();
            List<Category> listCateParent;
            List<Category> listCateChild;
            Category dopDowItem;
            listCateParent = db.Category.Where(o => o.ParentId == null).OrderBy(o => o.Id).ToList();

            foreach (Category item in listCateParent)
            {
                dopDowItem = new Category();
                listCateChild = db.Category.Where(o => o.ParentId == item.Id).ToList();
                if (listCateChild.Count > 0)
                {
                    listITem.Add(item);
                    foreach (Category itemCchild in listCateChild)
                    {
                        itemCchild.Name = "---- " + itemCchild.Name;
                        listITem.Add(itemCchild);
                    }
                }
                else
                {
                    listITem.Add(item);
                }
            }

            ViewBag.CategoryId = new SelectList(listITem, "Id", "Name", articles.CategoryId);
            ArticleViewModel viewmodel = new ArticleViewModel();
            viewmodel.articleInfo = articles;
            viewmodel.Description = articles.Description;
            viewmodel.Summary = articles.Summary;
            viewmodel.Description_EN = articles.Description_EN;
            viewmodel.Summary_EN = articles.Summary_EN;
            return View(viewmodel);
        }

        // POST: Articles/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [System.Web.Mvc.HttpPost]
        [ValidateAntiForgeryToken]
        //[ValidateAntiForgeryToken]
        public ActionResult Edit(ArticleViewModel articles, IEnumerable<HttpPostedFileBase> files)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var old = db.Articles.Find(articles.articleInfo.Id);
                    var fileName = string.Empty;
                    if (files != null)
                    {
                        foreach (var file in files)
                        {
                            if (file != null && file.ContentLength > 0)
                            {
                                try
                                {
                                    //kiem tra file extension lan nua
                                    List<string> excelExtension = new List<string>();
                                    excelExtension.Add(".png");
                                    excelExtension.Add(".jpg");
                                    excelExtension.Add(".gif");
                                    var extension = Path.GetExtension(file.FileName);
                                    if (!excelExtension.Contains(extension.ToLower()))
                                    {
                                        TempData["error"] = "File không đúng định dạng cho phép, bạn hãy chọn file có định dạng .jpg, gif hoặc png";
                                        return Json(new { success = 0, message = "File không đúng định dạng cho phép, bạn hãy chọn file có định dạng .jpg, gif hoặc png" });
                                    }
                                    //kiem tra dung luong file
                                    var fileSize = file.ContentLength;

VinCity/VinCity.CMS/Areas/Admin/Views/Articles/Create.cshtml
@using VinCity.Models.Entities;
@using VinCity.CMS.Areas.Admin.Models;
@model ArticleViewModel

@{
    ViewBag.Title = "Thêm mới bài viết";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

@section HeaderScript{
    <script src="~/Scripts/jquery-1.10.2.js"></script>
    <script src="~/Content/ckeditor/ckeditor.js"></script>
    <script src="~/Content/ckfinder/ckfinder.js"></script>

    <link href="~/Content/Bootstrap.min.css" rel="stylesheet" />
}

@section BreadCrumb{
    <ul class="breadcrumb">
        <li>
            <i class="ace-icon fa fa-home home-icon"></i>
            <a href="/Admin/HomeBackend">Trang chủ</a>
        </li>
        <li class="">
            <a href="/Admin/Articles">Danh sách bài viết</a>
        </li>
        <li class="">
            Thêm mới bài viết
        </li>
    </ul>
}
<div class="page-header">
    <h1>Thêm mới bài viết</h1>
</div>

@using (Html.BeginForm("Create", "Articles", FormMethod.Post, new { enctype = "multipart/form-data", id = "frmCreate" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <label class="control-label col-md-2">Tiêu đề</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.articleInfo.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.articleInfo.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            <label class="control-label col-md-2">Tiêu đề tiếng Anh</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.articleInfo.Title_EN, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.articleInfo.Title_EN, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            <label class="control-label col-md-2">Chuyên mục</label>
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.articleInfo.CategoryId, (SelectList)ViewBag.CategoryId, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.articleInfo.CategoryId, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-2">Tóm tắt</label>
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Summary, new { @id = "Summary" })
                <script>
                    // Replace the <textarea id="editor1"> with a CKEditor
                    // instance, using default configuration.

                    var editor = CKEDITOR.replace('Summary', {
                        enterMode: CKEDITOR.ENTER_BR,
                    });
                    CKFinder.setupCKEditor(null,'@Url.Content("~/Content/ckfinder/")');

                    //CKEDITOR.replace('Summary', {
                    //    filebrowserBrowseUrl: '/CKFinderScripts/ckfinder.html',
                    //    filebrowserImageBrowseUrl: '/CKFinderScripts/ckfinder.html?type=Images',
                    //    filebrowserUploadUrl: '/CKFinderScripts/connector?command=QuickUpload&type=Files',
                    //    filebrowserImageUploadUrl: '/CKFinderScripts/connector?command=QuickUpload&type=Images'
                    //});
                </script>
            </div>
        </div>

        @*<div class="form-group">
            <label class="control-label col-md-2">Tóm tắt tiếng Anh</label>
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Summary_EN, new { @id = "Summary_EN" })
                <script>
                    // Replace the <textarea id="editor1"> with a CKEditor
                    // instance, using default configuration.

                    var editor = CKEDITOR.replace('Summary_EN', {
                        enterMode: CKEDITOR.ENTER_BR,
                    });
                    CKFinder.setupCKEditor(null,'@Url.Content("~/Content/ckfinder/")');

                    //CKEDITOR.replace('Summary', {
                    //    filebrowserBrowseUrl: '/CKFinderScripts/ckfinder.html',
                    //    filebrowserImageBrowseUrl: '/CKFinderScripts/ckfinder.html?type=Images',
                    //    filebrowserUploadUrl: '/CKFinderScripts/connector?command=QuickUpload&type=Files',
                    //    filebrowserImageUploadUrl: '/CKFinderScripts/connector?command=QuickUpload&type=Images'
                    //});
                </script>
            </div>
        </div>*@

        <div class="form-group">
            <label class="control-label col-md-2">Chi tiết bài viết</label>
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Description, new { @id = "Description" })
                <script>
                    //Replace the <textarea id="editor1"> with a CKEditor
                    //instance, using default configuration.
                    //CKEDITOR.replace('Description', {
                    //    filebrowserBrowseUrl: '/CKFinderScripts/ckfinder.html',
                    //    filebrowserImageBrowseUrl: '/CKFinderScripts/ckfinder.html?type=Images',
                    //    filebrowserUploadUrl: '/CKFinderScripts/connector?command=QuickUpload&type=Files',
                    //    filebrowserImageUploadUrl: '/CKFinderScripts/connector?command=QuickUpload&type=Images'
                    //});

                    var editor = CKEDITOR.replace('Description', {
                        enterMode: CKEDITOR.ENTER_BR,
                    });
                    CKFinder.setupCKEditor(null, '@Url.Content("~/Content/ckfinder/")');
                </script>
            </div>
        </div>

        @*<div class="form-group">
            <label class="control-label col-md-2">Chi tiết bài viết tiếng Anh</label>
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Description_EN, new { @id = "Description_EN" })
                <script>
                    //Replace the <textarea id="editor1"> with a CKEditor
                    //instance, using default configuration.
                    //CKEDITOR.replace('Description', {
                    //    filebrowserBrowseUrl: '/CKFinderScripts/ckfinder.html',
                    //    filebrowserImageBrowseUrl: '/CKFinderScripts/ckfinder.html?type=Images',
                    //    filebrowserUploadUrl: '/CKFinderScripts/connector?command=QuickUpload&type=Files',
                    //    filebrowserImageUploadUrl: '/CKFinderScripts/connector?command=QuickUpload&type=Images'
                    //});

                    var editor = CKEDITOR.replace('Description_EN', {
                        enterMode: CKEDITOR.ENTER_BR,
                    });
                    CKFinder.setupCKEditor(null, '@Url.Content("~/Content/ckfinder/")');
                </script>
            </div>
        </div>*@

        <div class="form-group">
            <label class="control-label col-md-2">Ảnh tiêu đề</label>
            <div class="col-md-10">
                <input type="file" name="files" id="files" style="width: 100%;" /><br>
                <i style="font-size: 11px; font-style: italic;">File ảnh có định dạng .png, gif hoặc .jpg</i><br>
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Trạng thái</label>
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.articleInfo.Status, (SelectList)ViewBag.Status, new { @class = "form-control", @style = "witdth:150px;" })
                @Html.ValidationMessageFor(model => model.articleInfo.Status, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Lưu" class="btn btn-info btn-sm" />
                &nbsp;&nbsp;
                @Html.ActionLink("Quay lại danh sách", "Index", null, new { @class = "btn btn-info btn-sm" })
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

<script type="text/javascript">
    $('#frmCreate').on('submit', function () {
        for (instance in CKEDITOR.instances) {
            CKEDITOR.instances[instance].updateElement();
        }
    });
</script>

VinCity/VinCity.CMS/Areas/Admin/Views/Articles/Delete.cshtml
@model VinCity.Models.Entities.Article

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Article</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Summary)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Summary)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ThumbURL)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ThumbURL)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreateBy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreateBy)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UpdateBy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UpdateBy)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreateAt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreateAt)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UpdateAt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UpdateAt)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HotNew)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HotNew)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title_EN)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title_EN)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Summary_EN)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Summary_EN)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description_EN)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description_EN)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Category.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category.Name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

VinCity/VinCity.CMS/Areas/Admin/Views/Articles/Edit.cshtml
@using VinCity.Models.Entities;
@using VinCity.CMS.Areas.Admin.Models;
@using VinCity.CMS.Common;
@model ArticleViewModel

@{
    ViewBag.Title = "Sửa tin bài";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}
@section HeaderScript{
    <script src="~/Scripts/jquery-1.10.2.js"></script>
    @*<script src="~/Scripts/ckeditor/ckeditor.js"></script>*@

    <script src="~/Content/ckeditor/ckeditor.js"></script>
    <script src="~/Content/ckfinder/ckfinder.js"></script>
    <link href="~/Content/Bootstrap.min.css" rel="stylesheet" />
}
@section BreadCrumb{
    <ul class="breadcrumb">
        <li>
            <i class="ace-icon fa fa-home home-icon"></i>
            <a href="/Admin/HomeBackend">Trang chủ</a>
        </li>
        <li class="">
            <a href="/Admin/Articles">Danh sách bài viết</a>
        </li>
        <li class="">
            Sửa bài viết
        </li>
    </ul>
}
<div class="page-header">
    <h1>Sửa bài viết</h1>
</div>
@using (Html.BeginForm("Edit", "Articles", FormMethod.Post, new { enctype = "multipart/form-data", id = "frmCreate" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.HiddenFor(model => model.articleInfo.Id)
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <label class="control-label col-md-2">Tiêu đề</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.articleInfo.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.articleInfo.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            <label class="control-label col-md-2">Tiêu đề tiếng Anh</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.articleInfo.Title_EN, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.articleInfo.Title_EN, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            <label class="control-label col-md-2">Tóm tắt</label>
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Summary, new { @id = "Summary" })
                <script>

                    //// Replace the <textarea id="editor1"> with a CKEditor
                    //// instance, using default configuration.
                    //CKEDITOR.replace('Summary', {
                    //    filebrowserBrowseUrl: '/CKFinderScripts/ckfinder.html',
                    //    filebrowserImageBrowseUrl: '/CKFinderScripts/ckfinder.html?type=Images',
                    //    filebrowserUploadUrl: '/CKFinderScripts/connector?command=QuickUpload&type=Files',
                    //    filebrowserImageUploadUrl: '/CKFinderScripts/connector?command=QuickUpload&type=Images'
                    //});

                    var editor = CKEDITOR.replace('Summary', {
                        enterMode: CKEDITOR.ENTER_BR,
                    });
                    CKFinder.setupCKEditor(null, '@Url.Content("~/Content/ckfinder/")');
                </script>
            </div>
        </div>

        @*<div class="form-group">
            <label class="control-label col-md-2">Tóm tắt tiếng Anh</label>
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Summary_EN, new { @id = "Summary_EN" })
                <script>

                    //// Replace the <textarea id="editor1"> with a CKEditor
                    //// instance, using default configuration.
                    //CKEDITOR.replace('Summary', {
                    //    filebrowserBrowseUrl: '/CKFinderScripts/ckfinder.html',
                    //    filebrowserImageBrowseUrl: '/CKFinderScripts/ckfinder.html?type=Images',
                    //    filebrowserUploadUrl: '/CKFinderScripts/connector?command=QuickUpload&type=Files',
                    //    filebrowserImageUploadUrl: '/CKFinderScripts/connector?command=QuickUpload&type=Images'
                    //});

                    var editor = CKEDITOR.replace('Summary_EN', {
                        enterMode: CKEDITOR.ENTER_BR,
                    });
                    CKFinder.setupCKEditor(null, '@Url.Content("~/Content/ckfinder/")');
                </script>
            </div>
        </div>*@

        <div class="form-group">
            <label class="control-label col-md-2">Chi tiết bài viết</label>
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Description, new { @id = "Description" })

                <script>
                    //// Replace the <textarea id="editor1"> with a CKEditor
                    //// instance, using default configuration.
                    //CKEDITOR.replace('Description', {
                    //    filebrowserBrowseUrl: '/CKFinderScripts/ckfinder.html',
                    //    filebrowserImageBrowseUrl: '/CKFinderScripts/ckfinder.html?type=Images',
                    //    filebrowserUploadUrl: '/CKFinderScripts/connector?command=QuickUpload&type=Files',
                    //    filebrowserImageUploadUrl: '/CKFinderScripts/connector?command=QuickUpload&type=Images'
                    //});

                    var editor = CKEDITOR.replace('Description', {
                        enterMode: CKEDITOR.ENTER_BR,
                    });
                    CKFinder.setupCKEditor(null, '@Url.Content("~/Content/ckfinder/")');
                </script>
            </div>
        </div>

        @*<div class="form-group">
            <label class="control-label col-md-2">Chi tiết bài viết tiếng Anh</label>
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Description_EN, new { @id = "Description_EN" })

                <script>
                    //// Replace the <textarea id="editor1"> with a CKEditor
                    //// instance, using default configuration.
                    //CKEDITOR.replace('Description', {
                    //    filebrowserBrowseUrl: '/CKFinderScripts/ckfinder.html',
                    //    filebrowserImageBrowseUrl: '/CKFinderScripts/ckfinder.html?type=Images',
                    //    filebrowserUploadUrl: '/CKFinderScripts/connector?command=QuickUpload&type=Files',
                    //    filebrowserImageUploadUrl: '/CKFinderScripts/connector?command=QuickUpload&type=Images'
                    //});

                    var editor = CKEDITOR.replace('Description_EN', {
                        enterMode: CKEDITOR.ENTER_BR,
                    });
                    CKFinder.setupCKEditor(null, '@Url.Content("~/Content/ckfinder/")');
                </script>
            </div>
        </div>*@

        <div class="form-group">
            <label class="control-label col-md-2">Chuyên mục</label>
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.articleInfo.CategoryId, (SelectList)ViewBag.CategoryId, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.articleInfo.CategoryId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Ảnh tiêu đề</label>
            <div class="col-md-10">
                <input type="file" name="files" id="files" style="width: 100%;" /><br>
                @if (Model.articleInfo.ThumbURL != null)
                {
                    <div class="divimage">
                        <img src="@Utitlitys.ImagePath(Model.articleInfo.ThumbURL,(int)CMS_IMAGE_TYPE.ARTICLE_TYPE)" width="150px" />
                    </div>
                }
                <i style="font-size: 11px; font-style: italic;">File ảnh có định dạng .png, gif hoặc .jpg</i><br>
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Trạng thái</label>
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.articleInfo.Status, (SelectList)ViewBag.Status, new { @class = "form-control", @style = "witdth:150px;" })
                @Html.ValidationMessageFor(model => model.articleInfo.Status, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Lưu" class="btn btn-info btn-sm" />
                &nbsp;&nbsp;
                @Html.ActionLink("Quay lại danh sách", "Index", null, new { @class = "btn btn-info btn-sm" })
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}
<script type="text/javascript">
    $('#frmCreate').on('submit', function () {
        for (instance in CKEDITOR.instances) {
            CKEDITOR.instances[instance].updateElement();
        }
    });
</script>